//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValeraCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ord
    {
        public int IdOrder { get; set; }
        public string IdUser { get; set; }
        public string IdFilm { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
    }
}
